### PR TITLE
Changed setLight from private to public

### PR DESCRIPTION
**Pull request by aulvi**
I'd like to be able to use any RGB value on an LED but didn't see a way to do so w/the public API in the LED library. This is a teensy change to move the `setLight` function out of private scope.

Additionally, how do I test my work, build the firmware, etc? Any guidance here is welcomed, thanks!

### CODE REVIEW

**Comment by SaraJo** [comment]
here are some great ways to test: https://github.com/Jewelbots/arduino-library/wiki 

testing your change locally and then will deploy.

**Comment by SaraJo** [comment]
Hi! This hasn't been forgotten, we are working on making this open without causing the animations to stop working as things need to be enabled and disabled. Stay tuned!

**Comment by SaraJo** [comment]
Okay, we opened it up on our end and are working on an easier way to push and test. Sorry to not incorporate your pull request, we are working on making this friendlier for developers. Thank you for your help.

**Comment by aulvi** [comment]
Not a problem, thanks for following up!

**Pull request closed without merging**
