### PR TITLE
Control Buzzer duration

### PR DESCRIPTION
**Pull request by olore**
Taking a shot at #19. I'm not sure if we are allowed to change haptics_driver, but this seems to work ok.

Any feedback is appreciated!

### CODE REVIEW

**Comment by SaraJo** [comment]
Whoa, this is awesome. Myself or @davison-sm will test. There may be a delay because of the new year, excited about this.

**Comment by davison-sm** [comment]
Thanks for putting this together!  It is actually a great idea that I hadn't thought of.

I will need to do some investigation if this is 100% safe for the vibe motor.  If it is you are correct this would work out fine.  Maybe it would be worth creating a new, longer vibration sequence so that users have more flexibility, but that is pretty easy.

The only concern is that existing waveforms all return the vibe motor to zero amplitude at the end of each "buzz".  So there may be ill effects from arbitrarily cutting the vibe in the middle of a waveform.  

Thanks again, will definitely look into this further tomorrow when we get back into the office.

**Comment by olore** [comment]
Cool. Maybe instead of allowing any arbitrary length, we can figure out some options other than just long and short. Maybe extra-short, short, medium, long, extra-long using an enum. The flexibility would be nice, but we don't have to kill ourselves making it open ended.

**Comment by davison-sm** [comment]
As a temporary measure I just created additional buzz functions using the existing code structure.  There are now options for extra short, short, medium, long, extra long, and really long to cover the range of 125ms to 1.5 s.  

The haptics driver chip does have a mode that allows you to arbitrarily turn it on and off, but we don't have that mode implemented currently.  I will look into adding that mode to the current code base, but pushed out some additional options for the time being.

Thanks again for your suggestion, it was a novel idea and much appreciated!

**Comment by olore** [comment]
Looks great! A little more extensive than I thought, so thanks for implementing.

I think this closes #19.

**Pull request closed without merging**
