### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by bklang**
Fixes a typo in the Arduino example sketch

### CODE REVIEW

**Comment by glennblock** [comment]
👍

**Comment by bklang** [comment]
Fastest merge ever, and on Christmas Day to boot! Thanks!

**Comment by glennblock** [comment]
Thanks for taking the time to clean up the docs!

**Comment by glennblock** [comment]
Thanks for cleaning up the docs!

On Sun, Dec 25, 2016 at 3:36 PM Ben Klang <notifications@github.com> wrote:

Fastest merge ever, and on Christmas Day to boot! Thanks!




—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/Jewelbots/arduino-library/pull/17#issuecomment-269141829>,
or mute the thread

**Pull request merged**
