### PR TITLE
Add new colors to breathing animation

### LINKED ISSUE #29: Bring the new colors over to the breathing animation
The new colors are great! The breathing animation only contains the old ones, the animations code needs to be updated to make sure users can use breathe with the new colors. 

This code exists in the animations.cpp and animations.h files.

### PR DESCRIPTION
**Pull request by Loghorn**
Fixes #29 

Unfortunately, I don't have a Jewelbot to test the changes on, so it is possible I made something wrong and the new animations are completely off... in that case feel free to reject this PR 😃 

In any case, thank you for what you are doing!

### CODE REVIEW

**Comment by SaraJo** [comment]
WHOA SO COOL! Thanks, I'll take a look at this on a device. 

If you'd be interested in doing more we'd happily send you one!

**Comment by Loghorn** [comment]
Let me know if it works (I suspect the new animations are too bright compared to the existing one 😅)

I'd love so much to help you make Jewelbot even better 😃

**Comment by Loghorn** [comment]
@SaraJo, did you had the chance to test it?

**Comment by SaraJo** [comment]
Hi! I am (selfishly) holding off on merging it for filming a streaming event tomorrow. Will be tested/merged tomorrow!

**Comment by Loghorn** [comment]
No problem, take all the time you need: I was just worried something was wrong 😃

**Comment by SaraJo** [comment]
Works! Will release a new version of the library soon.

**Comment by Loghorn** [comment]
Great! Do you need me make a similar PR to the friendship library too?

**Pull request merged**
